In [1]:
#Using the processed dataset "Final_Groceries_dataset.csv" to proceed with the recommendation system
import pandas as pd
data=pd.read_csv('Final_Groceries_dataset.csv')

In [2]:
data

,Unnamed: 0,Customer_ID,Product_1,Product_2,Product_3,Product_4,Product_5,Product_6,Product_7,Product_8,...,Product_10,Product_11,Product_12,Product_13,Product_14,Product_15,Product_16,Product_17,Product_18,Product_19
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
2,2,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,3,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996,3996,3996,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3997,3997,3997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3998,3998,3998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3999,3999,3999,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4000,4000,4000,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [3]:
data=data.drop(['Unnamed: 0'],axis=1)

In [4]:
col=list(data.columns)

In [5]:
col=col[1:]

In [6]:
col

['Product_1',
 'Product_2',
 'Product_3',
 'Product_4',
 'Product_5',
 'Product_6',
 'Product_7',
 'Product_8',
 'Product_9',
 'Product_10',
 'Product_11',
 'Product_12',
 'Product_13',
 'Product_14',
 'Product_15',
 'Product_16',
 'Product_17',
 'Product_18',
 'Product_19']

In [7]:
#Helping Functions to calculate cosine
def square(col):
    sum=0
    for i in col:
        sum+=i*i
    return sum
def product(a,b):
    p=a*b
    return sum(p)

In [8]:
recommended=dict()
for i in col:
    recommended[i]=set()

### Slope one Algorithm
- Product to product recommendation.
- Use collaborative filtering technique.
- Calculate similarity of products between users

In [9]:
si=[]
for i in range(len(col)):
    for j in range(len(col)):
        if i!=j:
            similarity_index=product(data[col[i]],data[col[j]])
            similarity_index/=((sum(data[col[i]])*sum(data[col[j]]))**0.5)
            #si.append(index)
            if(similarity_index>=0.1):
               recommended[col[i]].add(col[j])

In [10]:
#si.sort(reverse=True)

In [11]:
recommended

{'Product_1': {'Product_10',
  'Product_11',
  'Product_16',
  'Product_19',
  'Product_2',
  'Product_4',
  'Product_6'},
 'Product_2': {'Product_1',
  'Product_10',
  'Product_11',
  'Product_16',
  'Product_19',
  'Product_4'},
 'Product_3': set(),
 'Product_4': {'Product_1',
  'Product_10',
  'Product_16',
  'Product_19',
  'Product_2'},
 'Product_5': {'Product_16'},
 'Product_6': {'Product_1', 'Product_16'},
 'Product_7': set(),
 'Product_8': set(),
 'Product_9': set(),
 'Product_10': {'Product_1', 'Product_16', 'Product_2', 'Product_4'},
 'Product_11': {'Product_1', 'Product_16', 'Product_2'},
 'Product_12': {'Product_16'},
 'Product_13': set(),
 'Product_14': set(),
 'Product_15': set(),
 'Product_16': {'Product_1',
  'Product_10',
  'Product_11',
  'Product_12',
  'Product_19',
  'Product_2',
  'Product_4',
  'Product_5',
  'Product_6'},
 'Product_17': set(),
 'Product_18': set(),
 'Product_19': {'Product_1', 'Product_16', 'Product_2', 'Product_4'}}

In [12]:
#Considering only the grocieries items
item=['brown bread','butter','cereals','coffee','detergent','flour','honey','house keeping products','mustard','oil','onions','pasta','rice','salt','soap','soda','spices','tea','white bread']

In [13]:
name=['Product_1','Product_2','Product_3','Product_4','Product_5','Product_6','Product_7','Product_8','Product_9','Product_10','Product_11','Product_12','Product_13','Product_14','Product_15','Product_16','Product_17','Product_18','Product_19']

In [14]:
print('Enter the product : ',end="")
p=input()
if name[item.index(p)] in recommended.keys():
    print('Recommendation :')
    for x in recommended[name[item.index(p)]]:
        print(item[name.index(x)])
    #print(recommended[item[name.index(name[item.index(p)]))

Enter the product : brown bread
Recommendation :
coffee
butter
soda
white bread
onions
oil
flour